apiVersion: v1
kind: Service
metadata:
  name: tomcat-mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql # must match the label of the pod, otherwise it will not be exposed
  type: ClusterIP
