apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat-mysql
  labels:
    app: mysql
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: aamir2292/mysql_mac
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
